language: java
jdk:
  - oraclejdk8
  - oraclejdk9
before_install:
  - cd Project
  - ls
script:
  - ant build.modules
  - ant build.all.artifacts
env:
  global:
  - 'SFTP_USER=artifacts'
  - 'SFTP_PASSWORD=ugent'
after_success:
- curl --ftp-create-dirs
       -T "/home/travis/build/tibovanheule/Lessenrooster/Project/__artifacts_temp/Project lessenrooster.jar"
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@46.101.81.61/usr/local/apache2/htdocs/tibo/artifacts
