language: java
jdk:
  - oraclejdk8
  - oraclejdk9
before_install:
  - cd Project
  - ls
script:
  - ant build.modules
  - ant build.all.artifacts
env:
  global:
  - 'SFTP_USER=artifacts'
  - 'SFTP_PASSWORD=ugent'
after_success:
- cd ../JAR/artifacts/Project_lessenrooster_jar
- ls
- curl --ftp-create-dirs
       -T "Project lessenrooster.jar" ftp://${SFTP_USER}:${SFTP_PASSWORD}@46.101.81.61
