language: java
jdk:
  - oraclejdk8
before_install:
  - cd Project
  - ls
script:
  - ant build.modules
  - ant build.all.artifacts
env:
  global:
  - 'SFTP_USER=artifacts'
  - 'SFTP_PASSWORD=ugent'
after_success:
- cd ../JAR/artifacts/ProjectLessenrooster_jar
- ls
- curl --ftp-create-dirs
       -T "ProjectLessenrooster.jar" ftp://${SFTP_USER}:${SFTP_PASSWORD}@46.101.81.61
- cd ../../../Project/javadoc
- find . -type f -exec curl -u ${SFTP_USER}:${SFTP_PASSWORD} --ftp-create-dirs -T {} ftp://46.101.81.61/javadoc/{} \;