language: java
jdk:
  - oraclejdk8
  - oraclejdk9
before_install:
  - cd Project
  - ls
script:
  - ant build.modules
  - ant build.all.artifacts
env:
  global:
  - 'SFTP_USER=artifacts'
  - 'SFTP_PASSWORD=ugent'
after_success:
- cd ../JAR/artifacts/Project_lessenrooster_jar
- ls
- sshpass -p ${SFTP_PASSWORD} scp -r "Project lessenrooster.jar" ${SFTP_USER}@46.101.81.61:/usr/local/apache2/htdocs/tibo/artifacts
